In [1]:
from matplotlib import pyplot
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler
df = pd.read_csv("multi-linear.csv")
df

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4  4000         5    8  760000

In [3]:
array = df.values

x = array[:,0:3]
y = array[:,3]

stdscaler = StandardScaler().fit(x)
stdscaledx = stdscaler.transform(x)

set_printoptions(precision = 3)
print(stdscaledx[:,:])

[[-1.407 -0.75   0.251]
 [-0.579  0.5   -0.447]
 [-0.166 -0.75  -0.028]
 [ 0.662 -0.75   1.647]
 [ 1.49   1.75  -1.423]]
